### ISSUE TITLE
[feature]作品詳細情報取得機能の実装

### ISSUE THREAD

**Issue by KeitaOsaki** [Funcy-ICT/Funcy_Portfolio_Backend#26]
## 機能概要
- 指定された作品の詳細情報を返す
## Taskリスト
-
## Doneの定義
- 想定したレスポンスであるか
## 参考リンク
- 
## 留意事項
- 
## 検討事項
-

**Comment by TadaTeruki** [comment]
**課題**
 - interface文で文字列処理が行われている(handlerでchiのURLParamを使う)
 - SQL文の書式が不安定で、大文字小文字の区別が正しくない部分がある
