### ISSUE TITLE
[feature]作品検索時にoptionでフィルタリングできるようにする

### ISSUE THREAD

**Issue by KeitaOsaki** [Funcy-ICT/Funcy_Portfolio_Backend#53]
## 機能概要
- /works/{number}/（作品一覧取得API）の後ろにクエリパラメータを付属して、タグに属する作品を引っ張ってくる
## Taskリスト
-
## Doneの定義
- クエリパラメータによってほしい作品を取得できるようにする
## 参考リンク
- 
## 留意事項
- tagについては検索機能として分類されていたが作品一覧取得機能に含めることとします
## 検討事項
-

**Comment by Justhiro55** [comment]
close
